class KillswitchEvent {
  final String id;
  final String userId;
  final DateTime triggeredAt;
  final String reason; // 'daily_loss'|'max_trades'|'revenge_pattern'|'overleveraging'|'fomo_pattern'
  final String accountMode;
  final int lockDurationMinutes;
  final bool unlockedEarly;
  final bool unlockedWithToken;
  final DateTime? resolvedAt;

  const KillswitchEvent({
    required this.id,
    required this.userId,
    required this.triggeredAt,
    required this.reason,
    required this.accountMode,
    required this.lockDurationMinutes,
    this.unlockedEarly = false,
    this.unlockedWithToken = false,
    this.resolvedAt,
  });

  factory KillswitchEvent.fromJson(Map<String, dynamic> json) {
    DateTime parseDate(String? s) {
      if (s == null || s.isEmpty) return DateTime.now();
      try { return DateTime.parse(s); } catch (_) { return DateTime.now(); }
    }
    return KillswitchEvent(
      id: json['id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      triggeredAt: parseDate(json['triggered_at'] as String?),
      reason: json['reason'] as String? ?? 'daily_loss',
      accountMode: json['account_mode'] as String? ?? 'personal',
      lockDurationMinutes: (json['lock_duration_minutes'] as num?)?.toInt() ?? 360,
      unlockedEarly: json['unlocked_early'] as bool? ?? false,
      unlockedWithToken: json['unlocked_with_token'] as bool? ?? false,
      resolvedAt: json['resolved_at'] != null
          ? parseDate(json['resolved_at'] as String?)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id' deliberately omitted — generated by Supabase on insert
      'user_id': userId,
      'triggered_at': triggeredAt.toIso8601String(),
      'reason': reason,
      'account_mode': accountMode,
      'lock_duration_minutes': lockDurationMinutes,
      'unlocked_early': unlockedEarly,
      'unlocked_with_token': unlockedWithToken,
      'resolved_at': resolvedAt?.toIso8601String(),
    };
  }

  String get reasonLabel {
    switch (reason) {
      case 'daily_loss':
        return 'Limite perdita giornaliera';
      case 'max_trades':
        return 'Max trade raggiunti';
      case 'revenge_pattern':
        return 'Revenge trading rilevato';
      case 'overleveraging':
        return 'Overleveraging rilevato';
      case 'fomo_pattern':
        return 'Pattern FOMO rilevato';
      default:
        return reason;
    }
  }

  String get reasonLabelEn {
    switch (reason) {
      case 'daily_loss': return 'Daily loss limit';
      case 'max_trades': return 'Max trades reached';
      case 'revenge_pattern': return 'Revenge trading detected';
      case 'overleveraging': return 'Overleveraging detected';
      case 'fomo_pattern': return 'FOMO pattern detected';
      default: return reason;
    }
  }

  String get reasonLabelIt {
    switch (reason) {
      case 'daily_loss': return 'Limite perdita giornaliera';
      case 'max_trades': return 'Max trade raggiunti';
      case 'revenge_pattern': return 'Revenge trading rilevato';
      case 'overleveraging': return 'Overleveraging rilevato';
      case 'fomo_pattern': return 'Pattern FOMO rilevato';
      default: return reason;
    }
  }

  bool get isActive => resolvedAt == null;

  static List<KillswitchEvent> get mockList => [
        KillswitchEvent(
          id: 'event-001',
          userId: 'test-user-001',
          triggeredAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
          reason: 'daily_loss',
          accountMode: 'personal',
          lockDurationMinutes: 360,
          unlockedEarly: false,
          unlockedWithToken: false,
          resolvedAt:
              DateTime.now().subtract(const Duration(days: 1, hours: 3)).add(
                    const Duration(hours: 6),
                  ),
        ),
        KillswitchEvent(
          id: 'event-002',
          userId: 'test-user-001',
          triggeredAt: DateTime.now().subtract(const Duration(days: 3)),
          reason: 'max_trades',
          accountMode: 'personal',
          lockDurationMinutes: 120,
          unlockedEarly: true,
          unlockedWithToken: true,
          resolvedAt:
              DateTime.now().subtract(const Duration(days: 3)).add(
                    const Duration(minutes: 30),
                  ),
        ),
        KillswitchEvent(
          id: 'event-003',
          userId: 'test-user-001',
          triggeredAt: DateTime.now().subtract(const Duration(days: 5)),
          reason: 'revenge_pattern',
          accountMode: 'challenge',
          lockDurationMinutes: 720,
          unlockedEarly: false,
          unlockedWithToken: false,
          resolvedAt:
              DateTime.now().subtract(const Duration(days: 5)).add(
                    const Duration(hours: 12),
                  ),
        ),
        KillswitchEvent(
          id: 'event-004',
          userId: 'test-user-001',
          triggeredAt: DateTime.now().subtract(const Duration(days: 7)),
          reason: 'fomo_pattern',
          accountMode: 'personal',
          lockDurationMinutes: 360,
          unlockedEarly: false,
          unlockedWithToken: false,
          resolvedAt:
              DateTime.now().subtract(const Duration(days: 7)).add(
                    const Duration(hours: 6),
                  ),
        ),
      ];
}
